### ISSUE TITLE
Error when trying to directly open a Journal file

### ISSUE THREAD

**Issue by Christoph27** [Open-Systems-Pharmacology/OSPSuite.Utility#30]
Double clicking on the attached Journal file generates the following Error. Opening from the MoBi project works though.

Application:
PK-Sim® 11.0.150

Object reference not set to an instance of an object.

Stack trace:
```
at OSPSuite.Presentation.Presenters.Diagram.BaseDiagramPresenter`3.Refresh()
   at OSPSuite.Presentation.Presenters.Journal.JournalDiagramPresenter.Handle(JournalPageUpdatedEvent eventToHandle)
   at OSPSuite.Utility.Events.EventPublisher.<>c__DisplayClass4_1`1.<PublishEvent>b__1()
   at OSPSuite.Utility.Exceptions.ExceptionManagerBase.Execute(Action action)


[Test.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.Utility/files/9147752/Test.zip)

**Comment by Christoph27** [comment]
the Journal file: 
[Test.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.Utility/files/9147778/Test.zip)
